sudo: false

matrix:
  allow_failures:
    - python: nightly

  include:
    - os: linux
      python: 3.5
      env: PYVER=3.5

    - os: linux
      python: 3.6
      env: PYVER=3.6

    - os: linux
      python: 3.7
      env: PYVER=3.7
      dist: xenial

    - os: linux
      python: 3.8
      env: PYVER=3.8 DEPLOY_PYPI=1
      dist: xenial

    - os: linux
      python: nightly
      env: PYVER=3.9
      dist: xenial

language: python

install:
  - pip install pip setuptools wheel flake8 mypy coveralls --upgrade
  - pip install .[dev]

script:
  - mypy --python-version $PYVER --strict --show-traceback --ignore-missing-imports --show-error-context --implicit-reexport --pretty -p destination
  - flake8 .
  - coverage run --source=destination setup.py test

after_success:
  - coveralls

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    user: "__token__"
    password:
      secure: "Vo3Obr6YhfcgdXSucjtQ3h4r6wksu7G92vnpGbT4F0OxdFLQbz2Je5Z5hy+/VEiwvNoJ+FKH29tOB0KZt3PA8bx8SGht0DB6T5zss2lhNJ5LC0pgerm5ev2NyVWZMWb27U1ANkabnLIh7jxrJgxvVsDORIEiTDsUrwWnC2muI6qnITZvaGwskTcpF09iXsTCDfe+2eq9YeREWOOPXhLh2pVUbHVr583rFAekzn3kRjcl1fu6ZWzFm0ZW85RPKld6LfpG2tZyJWrg6sr3woSQDZLzIiuokZ3DRRI1AG+qMR1Y5tzM/RxAGjiG368j//67nxQO6nKu9K7AUou1BPjXSbNo74is1gO4AseFpVMVXh9X1dsnLYVdCJkVcQpOGZZBlVfsEtMiPJ+4AkuXwi1aaggn3Ktkb8DwQQ4ys0CQ/GP0BzisStK2//YzMXOmKO0rl7/nTRW8krFuQ6Cp20jr5csxPiT4zrkSW2vlUPllQPgbOx8Vu4RlPnj124MSGHgU2up6Wx/w+7DE9TozNhJuVAcxrxw3p8UfH0KY078ucWasWOk+tOrehBR7hdgchxbmkfAsCi/MVBTYEj8ryJ+O62HUZwXDDBDqEeDbNzSr9FmYOY1LEieK67CqjOlgvRcEFAFEBoy6fDL97O6vOwSQY++0GBE5GrOGfTGWRxMeb8s="
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: master
      tags: false
      condition: "$DEPLOY_PYPI = 1"

  - provider: pypi
    distributions: sdist bdist_wheel
    user: "__token__"
    password:
      secure: "jks8Jlib5mU7XCgpNCkHKuMkrzTIIiLmTkWVBsfuaDQFD5UZ1JCArHaJCBhpnAFoJRYXz/1Igloh+1vi3t4AcmLsUgqZtuka310BmKuKzorYGZI2eBGQBxFEBaiGVZ33Pqn9xVoVDoB8gAAll//caRLqPvMyFGBvk9MnugdCNO+TQErgDrJWnzVH3EFF61P87v5T4/NsPUjK2uayYJ7OVAUe9guXrwP2R3vzmHLxETwIl0T2Oa4On0RDjJWCeT7pGmVrRraJ2qFYfPUay3WrsxGsSFNlhHiTpDwdTDtKk+JD95/RRMXrkQVHzx1P+yimQcRw47XZ1B69Dav8XvFFR/m5kP5xXQnF/wkpV6vnItniAvFWkfCWeCt7v4alSY8SV2k4O5hU3mTKw3v77co3S/QO0v6iFQBvCjt1LmzNmUyo4+2HU/R0sw0xUINoOirw7lc6NbZZTYTJrIL5uu6KYF9jwlN5+moa9obi1lTQi4XdBccrXoRT4ZvoJ70IHsBTB/uNCAX4kEYTmUQVzP7rptpSKGzSsXGl7BvcSQbv0N6Rpu4RJPpQaAjFjNoyMpN9+2EiwK8bK19NmM0qvLDkXZLDDHYa3yhs4CDhF7NKgSTa1EW4mLoVjH2UuMttGhxCdGmZcMNt9yAsWHQSQwPWYN+8Pmx05vvQhAE81xJjRHc="
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: master
      tags: true
      condition: "$DEPLOY_PYPI = 1"
